name: 'CI'

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.map.os }}
    strategy:
      matrix:
        map: [{os: windows-2022, host: windows, suffix: exe},
              {os: windows-2022, host: windows, suffix: zip}]
      fail-fast: false
    steps:
    - name: '❖ Fix default line endings on Windows'
      if: matrix.map.host == 'windows'
      run: git config --global core.autocrlf input

    - name: '⚙ Configure PATH on Windows'
      if: matrix.map.host == 'windows'
      run: |
        echo "C:\Program Files\Git\usr\bin" >> $GITHUB_PATH
      shell: bash

    - name: '⏳ Checkout repository'
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: '⬇ Install Qt on Windows'
      if: matrix.map.host == 'windows'
      uses: jurplel/install-qt-action@v4
      with:
        aqtsource: 'git+https://github.com/Kidev/aqtinstall.git@tools_ifw_fix'
        version: '6.5.1'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        dir: 'C:\Users\runneradmin'
        modules: 'qtimageformats qtserialport qt5compat'
        cache: true
        tools: 'tools_cmake tools_ifw tools_ninja tools_mingw90'

    - name: '🏗 Build IDE on Windows (.exe Installer)'
      if: matrix.map.host == 'windows' && matrix.map.suffix == 'exe'
      run: |
        python make.py --no-sign-application --no-sign-installer
      shell: bash

    - name: '🏗 Build IDE on Windows (.zip Portable)'
      if: matrix.map.host == 'windows' && matrix.map.suffix == 'zip'
      run: |
        python make.py --no-build-installer --no-sign-application --no-sign-installer
      shell: bash

    - name: '⬆ Upload artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: OpenMV-IDE-Windows-${{ matrix.map.suffix }}
        path: 'build/openmv-*.${{ matrix.map.suffix }}'
        if-no-files-found: error
