name: 'CI'

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
    - name: '❖ Fix default line endings on Windows'
      run: git config --global core.autocrlf input

    - name: '⚙ Configure PATH on Windows'
      run: |
        echo "C:\Program Files\Git\usr\bin" >> $GITHUB_PATH
      shell: bash

    - name: '⏳ Checkout repository'
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: '⬇ Install Qt on Windows'
      uses: jurplel/install-qt-action@v4
      with:
        aqtsource: 'git+https://github.com/Kidev/aqtinstall.git@tools_ifw_fix'
        version: '6.5.1'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        dir: 'C:\Users\runneradmin'
        modules: 'qtimageformats qtserialport qt5compat'
        cache: true
        tools: 'tools_cmake tools_ifw tools_ninja tools_mingw90'

    - name: '🏗 Build and Package OpenMV IDE'
      run: |
        python make.py --no-sign-application --no-sign-installer
      shell: bash

    - name: '⬆ Upload Windows Executables and Portable Archives'
      uses: actions/upload-artifact@v4
      with:
        name: OpenMV-IDE-Windows-Packages
        path: |
          build/openmv-*.exe
          build/openmv-*.zip
        if-no-files-found: warn
